services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: safepass1
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: safepass1
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            # Login
            - "15672:15672"
        volumes:
            - rabbitmq/var/lib/rabbitmq/data
volumes:
    pgdata:
    mongodata:
    rabbitmq:
