services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: safepass1
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: safepass1
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/var/lib/mongodb/data
volumes:
    pgdata:
    mongodata:
