services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: safepass1
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: safepass1
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            # Login
            - "15672:15672"
        volumes:
            - rabbitmq/var/lib/rabbitmq/data
    auction-svc:
        image: auction-svc:latest
        build:
            context: .
            dockerfile: src/AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=auction;Username=postgres;Password=safepass1
            - IdentityServiceUrl=http://identity-svc
        ports:
            - "5281:80"
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: search-svc:latest
        build:
            context: .
            dockerfile: src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://root:safepass1@mongodb:27017
            - AuctionServiceUrl=http://auction-svc
        ports:
            - "5169:80"
        depends_on:
            - mongodb
            - rabbitmq
    identity-svc:
        image: identity-svc:latest
        build:
            context: .
            dockerfile: src/IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=identity;Username=postgres;Password=safepass1
        ports:
            - "5002:80"
        depends_on:
            - postgres
    gateway-svc:
        image: gateway-svc:latest
        build:
            context: .
            dockerfile: src/GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - IdentityServiceUrl=http://identity-svc
        ports:
            - "5014:80"
volumes:
    pgdata:
    mongodata:
    rabbitmq:
